# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-04 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'arts')),
                ('category', models.CharField(max_length=100)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
