# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-10 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Msg',
        ),
    ]
